// File generated by Antigravity AI. Do not edit directly.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can configure this when needed.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for macOS.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for Windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbVIBF-16h2XuJK9ej6eWyMHhACnLT68c',
    appId: '1:286425881714:android:84e0cc801a3550a39cb6eb',
    messagingSenderId: '286425881714',
    projectId: 'signinpractice-bfade',
    storageBucket: 'signinpractice-bfade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA_ndTK0eVVDqTGgbZiaWODKuMzfKzthI',
    appId: '1:286425881714:ios:de99c20dbbc8a9a99cb6eb',
    messagingSenderId: '286425881714',
    projectId: 'signinpractice-bfade',
    storageBucket: 'signinpractice-bfade.firebasestorage.app',
    iosClientId: '286425881714-70lkul9ktqgfdhfe15kic37tf5ger3q1.apps.googleusercontent.com',
    iosBundleId: 'com.example.voidFactor',
  );
}
