// Renders the privacy policy to the static page Firebase Hosting serves.
//
//   dart run tool/privacy_policy_html.dart
//
// Google Play needs the policy at a public URL, and the app needs it readable
// without a browser. Rather than keep two documents honest by hand, the page is
// generated from `PrivacyPolicy` — the same constant the in-app screen reads —
// and `test/privacy_policy_test.dart` fails if the checked-in file is not what
// this produces today. Edit the policy, run this, commit both.
//
// Lives in tool/ rather than lib/ so no HTML rendering is compiled into the
// shipped app.

import 'dart:io';

import 'package:void_factor/features/legal/privacy_policy.dart';

/// Where the generated page is written, relative to the package root.
const String outputPath = 'firebase_hosting/public/privacy.html';

void main() {
  File(outputPath).writeAsStringSync(renderPrivacyPolicyHtml());
  stdout.writeln('wrote $outputPath');
}

/// The complete page. [sections] exists so a test can render something the real
/// policy does not contain; production callers pass nothing.
String renderPrivacyPolicyHtml({List<PolicySection>? sections}) {
  final body = (sections ?? PrivacyPolicy.sections).map(_section).join('\n');
  return '''
<!DOCTYPE html>
<!-- Generated by tool/privacy_policy_html.dart. Do not edit by hand: edit
     lib/features/legal/privacy_policy.dart and regenerate. -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy — ${_escape(PrivacyPolicy.appName)}</title>
    <meta name="description" content="How ${_escape(PrivacyPolicy.appName)} handles your data: what stays on your phone, what your account stores, and what happens to a food photo.">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;700;900&display=swap" rel="stylesheet">
    <style>
        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }
        body {
            font-family: 'Space Grotesk', sans-serif;
            background-color: #F9F9F9;
            color: #000000;
            display: flex;
            justify-content: center;
            padding: 24px;
        }
        .container {
            width: 100%;
            max-width: 720px;
            background-color: #FFFFFF;
            border: 3px solid #000000;
            box-shadow: 8px 8px 0px #000000;
            padding: 40px;
            margin: 24px 0;
        }
        .logo-box {
            display: inline-block;
            background-color: #000000;
            color: #FFFFFF;
            font-weight: 900;
            padding: 10px 20px;
            font-size: 20px;
            letter-spacing: 2px;
            border: 2px solid #000000;
        }
        h1 {
            font-size: 28px;
            font-weight: 900;
            letter-spacing: -1px;
            margin-top: 32px;
            text-transform: uppercase;
        }
        .divider {
            width: 80px;
            height: 4px;
            background-color: #000000;
            margin: 16px 0 16px 0;
        }
        .effective {
            font-size: 13px;
            font-weight: 700;
            letter-spacing: 1px;
            text-transform: uppercase;
            color: #777777;
            margin-bottom: 40px;
        }
        section {
            border-top: 2px solid #000000;
            padding-top: 24px;
            margin-bottom: 32px;
        }
        h2 {
            font-size: 15px;
            font-weight: 700;
            letter-spacing: 1px;
            text-transform: uppercase;
            margin-bottom: 16px;
        }
        p {
            font-size: 16px;
            line-height: 1.7;
            color: #333333;
            margin-bottom: 16px;
        }
        p:last-child {
            margin-bottom: 0;
        }
        footer {
            border-top: 2px solid #000000;
            padding-top: 24px;
            font-size: 13px;
            letter-spacing: 1px;
            text-transform: uppercase;
            color: #777777;
        }
        a {
            color: #000000;
        }
        @media (max-width: 560px) {
            body { padding: 0; }
            .container {
                border-width: 2px;
                box-shadow: none;
                padding: 24px;
                margin: 0;
            }
        }
    </style>
</head>
<body>
    <main class="container">
        <div class="logo-box">${_escape(PrivacyPolicy.appName.toUpperCase())}</div>
        <h1>Privacy Policy</h1>
        <div class="divider"></div>
        <p class="effective">Effective ${_escape(PrivacyPolicy.effectiveDate)}</p>
$body
        <footer>${_escape(PrivacyPolicy.appName)} — <a href="mailto:${_escape(PrivacyPolicy.contactEmail)}">${_escape(PrivacyPolicy.contactEmail)}</a></footer>
    </main>
</body>
</html>
''';
}

String _section(PolicySection section) {
  final paragraphs = section.paragraphs
      .map((p) => '            <p>${_escape(p)}</p>')
      .join('\n');
  return '        <section>\n'
      '            <h2>${_escape(section.title)}</h2>\n'
      '$paragraphs\n'
      '        </section>';
}

/// Policy text is prose, not markup. Anything that could be read as a tag or an
/// entity is escaped, so a stray `&` in a future edit cannot break the page.
String _escape(String text) => text
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
